version: "3.4"


services:
  app:
    environment:
      MYSQL_ENDPOINT: mysql://user:user@db:3306/db_ts
    depends_on:
      - db
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./app:/app
    command: >
      sh -c "
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: mysql:5.7
    hostname: db
    volumes: 
      - mysql-data:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: db_ts
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    container_name: ts_mysql_5.7
volumes: 
  mysql-data:

